// Code generated by "stringer -type=Level"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Info-0]
	_ = x[Error-1]
	_ = x[Fatal-2]
}

const _Level_name = "InfoErrorFatal"

var _Level_index = [...]uint8{0, 4, 9, 14}

func (i Level) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Level_index)-1 {
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Level_name[_Level_index[idx]:_Level_index[idx+1]]
}
